Checkpoint 5
DarylMcCullough/ez-events pull request #4
Opened 2017-07-07 23:22 UTC by DarylMcCullough

I have added the ability to view events from the show view for the registered app. Also, I now have the Heroku deployment working (the problem was that my code for setting up a default url was in environments/development, but not environments/production.) See the [Heroku version](https://ez-events.herokuapp.com). (But since seeds.rb doesn't run in production, there are no events to see.)

2017-07-08 02:34 UTC, brittanyjspringer requested changes

2017-07-08 02:34 UTC, wonderwoman13 commented on spec/controllers/registered_applications_controller_spec.rb
> +
@DarylMcCullough what is this? Please remove.

2017-07-08 02:34 UTC, wonderwoman13 commented on db/seeds.rb
> +    require 'faker'
I cloned down the repo, dropped the database and tried to seed it. 

I got: ActiveRecord::RecordInvalid: Validation failed: Name is too short (minimum is 5 characters)

2017-07-08 02:34 UTC, wonderwoman13 commented
@DarylMcCullough once this is all resolved, please reassign back to me. Thanks!

2017-07-08 21:32 UTC, DarylMcCullough commented on spec/controllers/registered_applications_controller_spec.rb
> +
I put that in by analogy from the Bloccit Checkpoint 19 spec for PostsController.show.

```
   describe "GET show" do
     it "returns http success" do
 # #16
       get :show, {id: my_post.id}
       expect(response).to have_http_status(:success)
     end
     it "renders the #show view" do
 # #17
       get :show, {id: my_post.id}
       expect(response).to render_template :show
     end
 
     it "assigns my_post to @post" do
       get :show, {id: my_post.id}
 # #18
       expect(assigns(:post)).to eq(my_post)
     end
   end
```

2017-07-08 21:43 UTC, DarylMcCullough commented on db/seeds.rb
> +    require 'faker'
Not sure how to force Faker to use longer names. I'm a little surprised that Faker would produce such a short name. Maybe there is something else going on? Anyway, assuming that the problem is with Faker sometimes generating too-short names, I put a loop in the seeds.db that keeps generating names until it gets one with more than 5 characters.

2017-07-08 21:47 UTC, DarylMcCullough commented on spec/controllers/registered_applications_controller_spec.rb
> +
The point of that line is that in the RegisteredApplicationsController, there is a line:

```
def show
         @registered_application = RegisteredApplication.find(params[:id])
...
```

This line is tested by writing
```
expect(assigns(:registered_application)).to eq(my_app)
```

where `my_app` is the app being "shown".

2017-07-09 15:50 UTC, wonderwoman13 commented
Tests pass and seeds work. Thanks!

2017-07-09 15:50 UTC, brittanyjspringer approved these changes

2017-07-09 15:50 UTC, merged