Checkpoint 6
DarylMcCullough/ez-events pull request #5
Opened 2017-07-10 21:19 UTC by DarylMcCullough

Implemented events_controller. Got API for posting events working, and one rspec test.

2017-07-10 21:25 UTC, DarylMcCullough commented
![coverage-2017-07-10](https://user-images.githubusercontent.com/8592134/28040715-a9b16e12-6594-11e7-9c16-61e29ac41ab7.jpg)

2017-07-10 21:26 UTC, brittanyjspringer requested changes

2017-07-10 21:26 UTC, wonderwoman13 commented on spec/controllers/api/events_controller_spec.rb
> +    end
@DarylMcCullough I'd like to see a test that shows that event is getting created on the POST, please. Otherwise, this is looking good!

2017-07-12 17:00 UTC, brittanyjspringer approved these changes

2017-07-12 17:00 UTC, merged